import { useCallback, useEffect, useState } from 'react'
import { useAuth } from '../auth/AuthContext.jsx'
import { PERMISSIONS } from '../auth/permissions.js'
import { CaseContactDialog, CaseEditDialog } from '../components/CaseDialogs.jsx'
import { DeletionRequestDialog } from '../components/DeletionRequestDialog.jsx'
import { FollowUpDialog } from '../components/FollowUpDialog.jsx'
import { Icon } from '../components/Icons.jsx'
import { ModalShell } from '../components/ModalShell.jsx'
import { StatusBadge } from '../components/StatusBadge.jsx'
import { TicketCreationFlow } from '../components/TicketCreationFlow.jsx'
import { caseHealthHelp, formatRate, rankCaseEmployees } from '../config/cases.js'
import { formatDateTime, humanizeActivity } from '../config/crm.js'
import { caseTicketService } from '../services/caseTicketService.js'
import { navigate } from '../utils/router.js'

const TABS = [
  ['overview','Overview'],['tickets','Tickets'],['timeline','Timeline'],['contacts','Contacts'],['performance','Performance'],
  ['employees','Employees'],['communications','Communications'],['followups','Follow-Ups'],['notes','Notes'],['documents','Documents'],['details','Details'],
]

function Metric({ label, value, hint }) { return <article className="case-stat"><span>{label}</span><strong>{value ?? 'N/A'}</strong>{hint && <small>{hint}</small>}</article> }
function Empty({ icon='file', title, children }) { return <div className="case-tab-empty"><Icon name={icon} size={28}/><h3>{title}</h3>{children && <p>{children}</p>}</div> }
function Health({ value }) { const label={HEALTHY:'Healthy',ATTENTION_NEEDED:'Attention Needed',AT_RISK:'At Risk'}[value]??'Healthy'; return <span className={`case-health health-${String(value).toLowerCase()}`} title={caseHealthHelp(value)}><i/>{label}</span> }

function CaseHeader({ data, canEdit, canCreate, canNote, onEdit, onCreate, onFollowUp, onNote, onContact, canContact, onDelete, canDelete }) {
  const metrics=data.metrics??{}; const initials=(data.displayName||data.companyName||'C').slice(0,2).toUpperCase()
  return <><button className="breadcrumb-link" onClick={()=>navigate('/console/cases')}>← Back to Cases</button><section className="case-profile-header">
    <div className="case-profile-main"><div className="case-logo">{data.logoUrl?<img src={data.logoUrl} alt=""/>:initials}</div><div><span className="section-kicker">CASE-{data.id.slice(0,8).toUpperCase()}</span><h1>{data.displayName||data.companyName}</h1><div className="case-header-badges"><span className="crm-badge">{data.status}</span><span className="crm-badge">{String(data.lifecycleStage).replaceAll('_',' ')}</span><Health value={data.health}/><span className={`priority-label priority-${data.priority}`}>{data.priority} priority</span></div></div></div>
    <div className="case-header-actions">{canCreate&&<button className="button button-primary" onClick={onCreate}><Icon name="plus" size={17}/>Create Ticket</button>}{canCreate&&<button className="button button-secondary" onClick={onFollowUp}><Icon name="calendar" size={17}/>Follow Up</button>}{canNote&&<button className="button button-secondary" onClick={onNote}>Add Note</button>}{canContact&&<button className="button button-secondary" onClick={onContact}>Add Contact</button>}{canEdit&&<button className="icon-button case-more-action" onClick={onEdit} aria-label="Edit Case"><Icon name="edit" size={18}/></button>}{canDelete&&<button className="icon-button case-more-action danger-text" onClick={onDelete} aria-label="Request Case deletion"><Icon name="trash" size={18}/></button>}</div>
    <dl className="case-header-info"><div><dt>Primary contact</dt><dd>{data.primaryContact?.name||'Not set'}</dd></div><div><dt>Phone</dt><dd>{data.primaryPhone||data.primaryContact?.phone||'Not set'}</dd></div><div><dt>Email</dt><dd>{data.primaryEmail||data.primaryContact?.email||'Not set'}</dd></div><div><dt>Owner</dt><dd>{data.ownerName||'Unassigned'}</dd></div><div><dt>Last interaction</dt><dd>{formatDateTime(metrics.lastInteraction)}</dd></div><div><dt>Next Follow Up</dt><dd>{formatDateTime(metrics.nextFollowUp)}</dd></div></dl>
  </section></>
}

function OverviewTab({ data, employees }) { const m=data.metrics??{}; const top=employees.find(e=>e.qualified)??employees[0]
  return <div className="case-overview-grid"><section className="case-section case-overview-metrics"><div className="case-section-heading"><h2>Relationship snapshot</h2><p>Calculated from authoritative Ticket outcomes and activity.</p></div><div className="case-stat-grid"><Metric label="Total Tickets" value={m.totalTickets??0}/><Metric label="Open Tickets" value={m.openTickets??0}/><Metric label="Won" value={m.wonTickets??0}/><Metric label="Lost" value={m.lostTickets??0}/><Metric label="Acceptance rate" value={formatRate(m.acceptanceRate)} hint="Accepted ÷ decided"/><Metric label="Win rate" value={formatRate(m.winRate)} hint="Won ÷ won + lost"/><Metric label="Avg. resolution" value={m.averageResolutionHours==null?'N/A':`${m.averageResolutionHours}h`}/><Metric label="Top employee" value={top?.name??'N/A'}/></div></section>
    <section className="case-section"><div className="case-section-heading"><h2>Attention</h2><p>Transparent operational signals.</p></div><div className="case-alert-list">{m.hasOverdueFollowUp&&<div className="case-alert warning"><Icon name="calendar" size={18}/><span><strong>Overdue Follow Up</strong><small>A scheduled activity has passed without completion.</small></span></div>}{data.riskLevel==='high'&&<div className="case-alert danger"><Icon name="activity" size={18}/><span><strong>High-risk Case</strong><small>Risk was explicitly set to high.</small></span></div>}{!m.hasOverdueFollowUp&&data.riskLevel!=='high'&&<div className="case-alert success"><Icon name="check" size={18}/><span><strong>No immediate alerts</strong><small>This Case has no overdue Follow Ups or high-risk flag.</small></span></div>}</div></section>
    <section className="case-section"><div className="case-section-heading"><h2>Recent Case activity</h2></div>{data.recentActivity?.length?<div className="compact-timeline">{data.recentActivity.map(item=><div key={item.id}><i/><span><strong>{humanizeActivity(item.action)}</strong><small>{item.actorName||'System'} · {formatDateTime(item.createdAt)}</small></span></div>)}</div>:<Empty title="No activity has been recorded."/>}</section>
    <section className="case-section case-about"><div className="case-section-heading"><h2>About this Case</h2></div><p>{data.description||'No company description has been added.'}</p><dl><div><dt>Industry</dt><dd>{data.industry||'Not set'}</dd></div><div><dt>Website</dt><dd>{data.website?<a href={data.website} target="_blank" rel="noreferrer">{data.website}</a>:'Not set'}</dd></div><div><dt>Sales manager</dt><dd>{data.salesManagerName||'Unassigned'}</dd></div><div><dt>Delivery manager</dt><dd>{data.deliveryManagerName||'Unassigned'}</dd></div></dl></section>
  </div>
}

function TicketsTab({ data, onCreate }) { return <section className="case-section"><div className="case-section-heading heading-actions"><div><h2>Complete Ticket history</h2><p>Operational records stay in the existing Ticket workspace.</p></div><button className="button button-primary button-small" onClick={onCreate}><Icon name="plus" size={16}/>Create Ticket</button></div>{data.items?.length?<div className="case-inner-table"><table><thead><tr><th>Ticket</th><th>Department</th><th>Stage</th><th>Status</th><th>Manager</th><th>Assigned</th><th>Updated</th></tr></thead><tbody>{data.items.map(t=><tr key={t.id} onClick={()=>navigate(`/console/tickets/${t.id}`)}><td><strong>{t.projectTitle}</strong><small>{t.id.slice(0,8).toUpperCase()}</small></td><td>{t.currentDepartment}</td><td><StatusBadge value={t.stage} kind="stage"/></td><td><StatusBadge value={t.status}/></td><td>{t.responsibleManagerName||'—'}</td><td>{t.assignedUsers?.map(u=>u.name).join(', ')||'None'}</td><td>{formatDateTime(t.updatedAt)}</td></tr>)}</tbody></table></div>:<Empty title="No tickets are associated with this Case.">Create the first Ticket to start its operational history.</Empty>}</section> }

function TimelineTab({ items, category, onCategory }) { return <section className="case-section"><div className="case-section-heading"><h2>Unified activity timeline</h2><div className="case-filter-pills">{['ALL','TICKET','EMAIL','CALL','FOLLOW_UP','NOTE','CASE'].map(v=><button key={v} className={category===v?'active':''} onClick={()=>onCategory(v)}>{v.replaceAll('_',' ')}</button>)}</div></div>{items.length?<div className="case-timeline">{items.map(item=><article key={`${item.category}-${item.id}`}><div className="case-timeline-marker"><i/></div><div><span className="crm-badge">{item.category.replaceAll('_',' ')}</span><h3>{humanizeActivity(item.title)}</h3><p>{item.details?.purpose||item.details?.subject||item.details?.content||item.details?.preview||'Activity recorded in LeadSphere.'}</p><small>{item.actorName||'System'} · {formatDateTime(item.createdAt)}{item.ticketId&&<> · <button onClick={()=>navigate(`/console/tickets/${item.ticketId}`)}>Open Ticket</button></>}</small></div></article>)}</div>:<Empty title="No activity has been recorded."/>}</section> }

function ContactsTab({ items, canManage, onAdd, onEdit }) { return <section className="case-section"><div className="case-section-heading heading-actions"><div><h2>Contacts</h2><p>One Case address book, synchronized from Ticket contacts.</p></div>{canManage&&<button className="button button-primary button-small" onClick={onAdd}><Icon name="plus" size={16}/>Add Contact</button>}</div>{items.length?<div className="contact-card-grid">{items.map(c=><article key={c.id} className={c.status==='inactive'?'muted':''}><div className="avatar">{c.name.slice(0,2).toUpperCase()}</div><div><h3>{c.name}{c.primary&&<span>Primary</span>}</h3><p>{[c.jobTitle,c.department].filter(Boolean).join(' · ')||'Contact'}</p><a href={c.email?`mailto:${c.email}`:`tel:${c.phone}`}>{c.email||c.phone}</a>{c.phone&&c.email&&<small>{c.phone}</small>}</div>{canManage&&<button className="icon-button" onClick={()=>onEdit(c)} aria-label={`Edit ${c.name}`}><Icon name="edit" size={16}/></button>}</article>)}</div>:<Empty icon="users" title="No contacts have been added."/>}</section> }

function PerformanceTab({ data, employees }) { const m=data.metrics??{}; const bars=[['Accepted',m.acceptedTickets],['Rejected',m.rejectedTickets],['Won',m.wonTickets],['Lost',m.lostTickets],['Open',m.openTickets]]; const max=Math.max(1,...bars.map(([,v])=>Number(v)||0)); return <div className="case-performance-grid"><section className="case-section"><div className="case-section-heading"><h2>Outcome performance</h2><p>Pending Tickets are excluded from rate denominators.</p></div><div className="case-stat-grid"><Metric label="Acceptance rate" value={formatRate(m.acceptanceRate)}/><Metric label="Win rate" value={formatRate(m.winRate)}/><Metric label="Decided Tickets" value={(m.acceptedTickets??0)+(m.rejectedTickets??0)}/><Metric label="Concluded outcomes" value={(m.wonTickets??0)+(m.lostTickets??0)}/></div><div className="case-bar-chart" aria-label="Ticket outcomes">{bars.map(([label,value])=><div key={label}><span>{label}</span><i><b style={{width:`${(Number(value)||0)/max*100}%`}}/></i><strong>{value??0}</strong></div>)}</div></section><section className="case-section"><div className="case-section-heading"><h2>Employee outcome leaders</h2><p>Win rate is weighted with outcomes, acceptance, and volume confidence.</p></div>{employees.length?<div className="leader-list">{employees.slice(0,5).map((e,i)=><div key={e.userId}><span>{i+1}</span><strong>{e.name}</strong><small>{e.won} won · {formatRate(e.winRate)} win rate</small>{!e.qualified&&<em>Small sample</em>}</div>)}</div>:<Empty title="Not enough completed tickets to calculate employee performance."/>}</section></div> }

function EmployeesTab({ items }) { return <section className="case-section"><div className="case-section-heading"><h2>Employees connected to this Case</h2><p>Ranking requires three concluded Tickets when sufficient history exists; raw metrics remain visible.</p></div>{items.length?<div className="case-inner-table"><table><thead><tr><th>Rank / Employee</th><th>Roles</th><th>Handled</th><th>Won</th><th>Lost</th><th>Win rate</th><th>Acceptance</th><th>Last interaction</th></tr></thead><tbody>{items.map((e,i)=><tr key={e.userId}><td><strong>#{i+1} {e.name}</strong>{!e.qualified&&<small>Small-sample ranking</small>}</td><td>{e.roles?.join(', ')||'Team member'}</td><td>{e.ticketsHandled}</td><td>{e.won}</td><td>{e.lost}</td><td>{formatRate(e.winRate)}</td><td>{formatRate(e.acceptanceRate)}</td><td>{formatDateTime(e.lastInteraction)}</td></tr>)}</tbody></table></div>:<Empty title="No employees have interacted with this Case."/>}</section> }

function CommunicationsTab({ items, filter, onFilter }) { return <section className="case-section"><div className="case-section-heading"><h2>Communications</h2><div className="case-filter-pills">{[['','All'],['EMAIL','Email'],['CALL','Calls']].map(([v,l])=><button key={l} className={filter===v?'active':''} onClick={()=>onFilter(v)}>{l}</button>)}</div></div>{items.length?<div className="communication-list">{items.map(c=><article key={c.id}><span className="feature-icon"><Icon name={c.category==='EMAIL'?'mail':'phone'} size={17}/></span><div><span>{c.eventType.replaceAll('_',' ')}</span><h3>{c.subject||c.preview||c.notes||`${c.category} activity`}</h3><p>{c.userName||'Team member'} · {c.direction.toLowerCase()} · {c.status}</p></div><div><time>{formatDateTime(c.occurredAt)}</time><button onClick={()=>navigate(`/console/tickets/${c.ticketId}`)}>Open Ticket</button></div></article>)}</div>:<Empty title="No communications have been recorded."/>}</section> }

function FollowUpsTab({ items, onAdd }) { return <section className="case-section"><div className="case-section-heading heading-actions"><div><h2>Follow-Ups</h2><p>Upcoming, overdue, completed, cancelled, and recurring activities.</p></div><button className="button button-primary button-small" onClick={onAdd}><Icon name="plus" size={16}/>Add Follow Up</button></div>{items.length?<div className="followup-case-list">{items.map(f=><article key={f.id} className={f.overdue?'overdue':''}><span className="feature-icon"><Icon name={f.type==='EMAIL'?'mail':f.type==='CALL'?'phone':'calendar'} size={17}/></span><div><span>{f.type} {f.recurring&&'· Recurring'}</span><h3>{f.purpose||'Scheduled Follow Up'}</h3><p>{f.ticketTitle} · {formatDateTime(f.scheduledAt)}</p></div><StatusBadge value={f.overdue?'overdue':f.status}/><button onClick={()=>navigate(`/console/tickets/${f.ticketId}`)}>Open Ticket</button></article>)}</div>:<Empty icon="calendar" title="No Follow Ups are associated with this Case."/>}</section> }

function NotesTab({ items, tickets, canAdd, onSaved }) { const [content,setContent]=useState('');const [ticketId,setTicketId]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const submit=async(e)=>{e.preventDefault();if(!content.trim())return;setBusy(true);setError('');try{await onSaved(ticketId,content);setContent('');setTicketId('')}catch(err){setError(err.message)}finally{setBusy(false)}};return <div className="case-notes-grid">{canAdd&&<section className="case-section"><div className="case-section-heading"><h2>Add internal note</h2></div>{error&&<div className="alert alert-error">{error}</div>}<form onSubmit={submit}><label className="field"><span>Related Ticket <small>(optional)</small></span><select value={ticketId} onChange={e=>setTicketId(e.target.value)}><option value="">Case-level note</option>{tickets.map(t=><option key={t.id} value={t.id}>{t.projectTitle}</option>)}</select></label><label className="field"><span>Note</span><textarea rows="5" maxLength="5000" value={content} onChange={e=>setContent(e.target.value)} placeholder="Add useful internal context…"/></label><button className="button button-primary" disabled={busy||!content.trim()}>{busy?'Saving…':'Add Note'}</button></form></section>}<section className="case-section"><div className="case-section-heading"><h2>Note history</h2></div>{items.length?<div className="case-note-list">{items.map(n=><article key={n.id}><p>{n.content}</p><small>{n.authorName} · {formatDateTime(n.createdAt)}{n.ticketTitle&&` · ${n.ticketTitle}`}</small></article>)}</div>:<Empty title="No notes have been added."/>}</section></div> }

function DetailsTab({ data }) { const rows=[['Registered name',data.legalName],['Industry',data.industry],['Company type',data.companyType],['Website',data.website],['Email',data.primaryEmail],['Additional emails',data.additionalEmails?.join(', ')],['Phone',data.primaryPhone],['Additional phones',data.additionalPhones?.join(', ')],['Address',[data.address,data.city,data.region,data.country].filter(Boolean).join(', ')],['Company size',data.companySize],['Employees',data.employeeCount],['Annual revenue',data.annualRevenue],['Source',data.source],['First contact',data.firstContactDate],['Account owner',data.ownerName],['Sales manager',data.salesManagerName],['Delivery manager',data.deliveryManagerName],['Created by',data.createdByName],['Created',formatDateTime(data.createdAt)],['Updated',formatDateTime(data.updatedAt)]];return <section className="case-section"><div className="case-section-heading"><h2>Case details</h2></div><dl className="case-detail-list">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not set'}</dd></div>)}</dl>{data.tags?.length>0&&<div className="case-tags">{data.tags.map(tag=><span key={tag}>{tag}</span>)}</div>}</section> }

export function CaseDetailPage({ caseId }) {
  const { can }=useAuth(); const [data,setData]=useState(null);const [reference,setReference]=useState({});const [tickets,setTickets]=useState({items:[]});const [employees,setEmployees]=useState([]);const [tab,setTab]=useState('overview');const [tabData,setTabData]=useState({});const [loading,setLoading]=useState(true);const [tabLoading,setTabLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [timelineCategory,setTimelineCategory]=useState('ALL');const [communicationFilter,setCommunicationFilter]=useState('');const [creationOpen,setCreationOpen]=useState(false);const [editOpen,setEditOpen]=useState(false);const [contactDialog,setContactDialog]=useState(null);const [deleteOpen,setDeleteOpen]=useState(false);const [followPicker,setFollowPicker]=useState(false);const [followTicket,setFollowTicket]=useState(null);const [busy,setBusy]=useState(false)
  const mayEdit=can(PERMISSIONS.CASES_UPDATE),mayCreate=can(PERMISSIONS.TICKETS_CREATE),mayContact=can(PERMISSIONS.CASE_CONTACTS_MANAGE),mayNote=can(PERMISSIONS.CASE_NOTES_CREATE),mayDelete=can(PERMISSIONS.CASES_DELETE_REQUEST)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [overview,ref,ticketData,employeeData]=await Promise.all([caseTicketService.getCaseOverview(caseId),caseTicketService.getReferenceData(),caseTicketService.listCaseTickets(caseId,{pageSize:100}),caseTicketService.listCaseEmployees(caseId)]);setData(overview);setReference(ref);setTickets(ticketData);setEmployees(rankCaseEmployees(employeeData))}catch{setError('This Case could not be loaded or you do not have access to it.')}finally{setLoading(false)}},[caseId])
  useEffect(()=>{load()},[load])
  const loadTab=useCallback(async(target=tab)=>{if(!data||['overview','performance','employees','details','tickets'].includes(target))return;setTabLoading(true);try{let result;if(target==='timeline')result=await caseTicketService.getCaseTimeline(caseId,timelineCategory);if(target==='contacts')result=await caseTicketService.listCaseContacts(caseId);if(target==='communications')result=await caseTicketService.listCaseCommunications(caseId,communicationFilter);if(target==='followups')result=await caseTicketService.listCaseFollowUps(caseId);if(target==='notes')result=await caseTicketService.listCaseNotes(caseId);if(target==='documents')result=(await caseTicketService.listCaseCommunications(caseId,'')).filter(item=>item.hasAttachments);setTabData(current=>({...current,[target]:result??[]}))}catch{setError('This Case section could not be loaded. Please try again.')}finally{setTabLoading(false)}},[caseId,communicationFilter,data,tab,timelineCategory])
  useEffect(()=>{loadTab(tab)},[loadTab,tab])
  const saved=async(messageText)=>{setMessage(messageText);await load();await loadTab(tab)}
  const requestDeletion=async({managerId,note})=>{setBusy(true);try{await caseTicketService.requestCaseDeletion(caseId,managerId,note);setDeleteOpen(false);setMessage('Delete Case request submitted to the selected manager.')}catch(err){setError(err.message);setDeleteOpen(false)}finally{setBusy(false)}}
  if(loading)return <div className="console-content"><div className="loading-state panel-loading">Loading Case 360…</div></div>
  if(!data)return <div className="console-content"><div className="alert alert-error">{error}<button className="text-button" onClick={load}>Retry</button></div></div>
  let content;if(tab==='overview')content=<OverviewTab data={data} employees={employees}/>;if(tab==='tickets')content=<TicketsTab data={tickets} onCreate={()=>setCreationOpen(true)}/>;if(tab==='timeline')content=<TimelineTab items={tabData.timeline??[]} category={timelineCategory} onCategory={value=>{setTimelineCategory(value);setTabData(c=>({...c,timeline:undefined}))}}/>;if(tab==='contacts')content=<ContactsTab items={tabData.contacts??[]} canManage={mayContact} onAdd={()=>setContactDialog({})} onEdit={setContactDialog}/>;if(tab==='performance')content=<PerformanceTab data={data} employees={employees}/>;if(tab==='employees')content=<EmployeesTab items={employees}/>;if(tab==='communications')content=<CommunicationsTab items={tabData.communications??[]} filter={communicationFilter} onFilter={setCommunicationFilter}/>;if(tab==='followups')content=<FollowUpsTab items={tabData.followups??[]} onAdd={()=>setFollowPicker(true)}/>;if(tab==='notes')content=<NotesTab items={tabData.notes??[]} tickets={tickets.items??[]} canAdd={mayNote} onSaved={async(ticketId,note)=>{await caseTicketService.addCaseNote(caseId,ticketId,note);await saved('Case note added.')}}/>;if(tab==='documents')content=<section className="case-section"><div className="case-section-heading"><h2>Documents and attachments</h2><p>Files recorded through the existing communication system.</p></div>{(tabData.documents??[]).length?<div className="communication-list">{tabData.documents.map(item=><article key={item.id}><Icon name="file"/><div><h3>{item.subject||'Communication attachment'}</h3><p>{item.category} · {formatDateTime(item.occurredAt)}</p></div><button onClick={()=>navigate(`/console/tickets/${item.ticketId}`)}>Open Ticket</button></article>)}</div>:<Empty title="No attachments are associated with this Case."/>}</section>;if(tab==='details')content=<DetailsTab data={data}/>
  return <div className="console-content case-profile-page"><CaseHeader data={data} canEdit={mayEdit} canCreate={mayCreate} canNote={mayNote} canContact={mayContact} canDelete={mayDelete} onEdit={()=>setEditOpen(true)} onCreate={()=>setCreationOpen(true)} onFollowUp={()=>setFollowPicker(true)} onNote={()=>setTab('notes')} onContact={()=>setContactDialog({})} onDelete={()=>setDeleteOpen(true)}/>{error&&<div className="alert alert-error" role="alert">{error}<button className="text-button" onClick={()=>{setError('');loadTab(tab)}}>Retry</button></div>}{message&&<div className="alert alert-success" role="status">{message}</div>}
    <nav className="case-tabs" aria-label="Case sections">{TABS.map(([value,label])=><button key={value} className={tab===value?'active':''} onClick={()=>{setTab(value);setError('')}}>{label}</button>)}</nav><div className="case-tab-content">{tabLoading?<div className="case-table-loading">Loading {TABS.find(([value])=>value===tab)?.[1]}…</div>:content}</div>
    {creationOpen&&<TicketCreationFlow fixedCase={{id:data.id,companyName:data.companyName}} onClose={()=>setCreationOpen(false)} onCreated={result=>navigate(`/console/tickets/${result.ticketId}`)}/>} {editOpen&&<CaseEditDialog caseData={data} reference={reference} onClose={()=>setEditOpen(false)} onSave={changes=>caseTicketService.updateCase(caseId,changes).then(()=>saved('Case profile updated.'))}/>} {contactDialog&&<CaseContactDialog contact={contactDialog.id?contactDialog:null} onClose={()=>setContactDialog(null)} onSave={(id,contact)=>caseTicketService.saveCaseContact(caseId,id,contact).then(()=>saved(id?'Contact updated.':'Contact added.'))}/>} {deleteOpen&&<DeletionRequestDialog kind="case" name={data.companyName} ticketCount={tickets.total??0} managers={reference.managers??[]} busy={busy} onClose={()=>setDeleteOpen(false)} onSubmit={requestDeletion}/>}
    {followPicker&&<ModalShell title="Select a Ticket" kicker="Case Follow Up" onClose={()=>setFollowPicker(false)}><p>Follow Ups remain linked to a Ticket so existing permissions, recurrence, and reminders continue to work.</p><div className="case-choice-list">{tickets.items?.filter(t=>t.status==='active').map(t=><button key={t.id} onClick={()=>{setFollowTicket({...t,companyName:data.companyName,number:t.id.slice(0,8),title:t.projectTitle});setFollowPicker(false)}}><span><strong>{t.projectTitle}</strong><small>{t.currentDepartment} · {t.stage}</small></span><Icon name="arrow"/></button>)}{!tickets.items?.some(t=>t.status==='active')&&<Empty title="No active Ticket is available for a Follow Up."/>}</div></ModalShell>}{followTicket&&<FollowUpDialog ticket={followTicket} onClose={()=>setFollowTicket(null)} onSaved={async()=>{setFollowTicket(null);await saved('Follow Up created.');setTab('followups')}}/>}
  </div>
}
