-- Persist user-specific workflow notifications. Permission-request lifecycle
-- events are generated by database triggers so every client receives the same
-- trustworthy result.

create table if not exists public.user_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  title text not null,
  message text not null,
  link text,
  event_key text not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint user_notifications_kind_length check (char_length(kind) between 2 and 60),
  constraint user_notifications_title_length check (char_length(title) between 2 and 140),
  constraint user_notifications_message_length check (char_length(message) between 2 and 500),
  constraint user_notifications_event_unique unique (user_id, event_key)
);

create index if not exists user_notifications_user_recent_idx
  on public.user_notifications (user_id, created_at desc);
create index if not exists user_notifications_user_unread_idx
  on public.user_notifications (user_id, created_at desc)
  where read_at is null;

alter table public.user_notifications enable row level security;
drop policy if exists user_notifications_read_own on public.user_notifications;
create policy user_notifications_read_own on public.user_notifications
for select to authenticated using (user_id = (select auth.uid()));
drop policy if exists user_notifications_update_own on public.user_notifications;
create policy user_notifications_update_own on public.user_notifications
for update to authenticated using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create or replace function public.crm_notification_request_label(p_type text)
returns text language sql immutable set search_path = '' as $$
  select case p_type
    when 'ASSIGN_TO_ME' then 'Assignment'
    when 'POST_TICKET' then 'Ticket transfer'
    when 'DELETE_TICKET' then 'Ticket deletion'
    when 'DELETE_CASE' then 'Case deletion'
    else 'Permission'
  end;
$$;

create or replace function public.crm_notify_permission_request_created()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  requester_name text;
  record_name text;
  destination text;
begin
  select coalesce(profile.display_name, profile.email::text, 'A team member')
  into requester_name from public.profiles profile where profile.id = new.requested_by_user_id;

  if new.request_type = 'DELETE_CASE' then
    select company.company_name into record_name from public.crm_cases company where company.id = new.case_id;
    destination := '/console/cases/' || new.case_id::text;
  else
    select ticket.project_title into record_name from public.crm_tickets ticket where ticket.id = new.ticket_id;
    destination := '/console/tickets/' || new.ticket_id::text;
  end if;

  if new.assigned_manager_id is distinct from new.requested_by_user_id then
    insert into public.user_notifications (user_id, kind, title, message, link, event_key)
    values (
      new.assigned_manager_id,
      'permission_request',
      public.crm_notification_request_label(new.request_type) || ' request',
      requester_name || ' submitted a request for ' || coalesce(record_name, 'a CRM record') || '.',
      destination,
      'permission-request-created:' || new.id::text
    ) on conflict (user_id, event_key) do nothing;
  end if;
  return new;
end;
$$;

create or replace function public.crm_notify_permission_request_reviewed()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  record_name text;
  destination text;
  decision_label text;
begin
  if old.status is not distinct from new.status or new.status = 'PENDING' then return new; end if;
  decision_label := case new.status when 'APPROVED' then 'approved' when 'REJECTED' then 'rejected' when 'MODIFIED' then 'approved with changes' else lower(new.status) end;

  if new.request_type = 'DELETE_CASE' then
    select company.company_name into record_name from public.crm_cases company where company.id = new.case_id;
    destination := case when new.status = 'APPROVED' then '/console/leads' else '/console/cases/' || new.case_id::text end;
  else
    select ticket.project_title into record_name from public.crm_tickets ticket where ticket.id = new.ticket_id;
    destination := case when new.request_type = 'DELETE_TICKET' and new.status = 'APPROVED'
      then '/console/leads' else '/console/tickets/' || new.ticket_id::text end;
  end if;

  insert into public.user_notifications (user_id, kind, title, message, link, event_key)
  values (
    new.requested_by_user_id,
    'permission_' || lower(new.status),
    public.crm_notification_request_label(new.request_type) || ' ' || decision_label,
    'Your request for ' || coalesce(record_name, 'a CRM record') || ' was ' || decision_label || '.',
    destination,
    'permission-request-reviewed:' || new.id::text || ':' || new.status
  ) on conflict (user_id, event_key) do nothing;
  return new;
end;
$$;

create or replace function public.crm_notify_ticket_activity()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  ticket_record public.crm_tickets%rowtype;
  notification_title text;
  notification_message text;
  destination text;
begin
  if new.action <> all(array['TICKET_CREATED','NOTE_ADDED','ASSIGNMENT_DIRECT','TRANSFER_DIRECT','TICKET_CLOSED','TICKET_DELETE_DIRECT']) then return new; end if;
  select * into ticket_record from public.crm_tickets where id = new.ticket_id;
  if ticket_record.id is null then return new; end if;

  notification_title := case new.action
    when 'TICKET_CREATED' then 'Ticket created'
    when 'NOTE_ADDED' then 'New Ticket note'
    when 'ASSIGNMENT_DIRECT' then 'Ticket assignment updated'
    when 'TRANSFER_DIRECT' then 'Ticket transferred'
    when 'TICKET_CLOSED' then 'Ticket closed'
    when 'TICKET_DELETE_DIRECT' then 'Ticket archived'
  end;
  notification_message := case new.action
    when 'TICKET_CREATED' then ticket_record.project_title || ' was created.'
    when 'NOTE_ADDED' then 'A note was added to ' || ticket_record.project_title || '.'
    when 'ASSIGNMENT_DIRECT' then ticket_record.project_title || ' has a new direct assignment.'
    when 'TRANSFER_DIRECT' then ticket_record.project_title || ' moved to another department.'
    when 'TICKET_CLOSED' then ticket_record.project_title || ' was closed.'
    when 'TICKET_DELETE_DIRECT' then ticket_record.project_title || ' was archived.'
  end;
  destination := case when new.action = 'TICKET_DELETE_DIRECT'
    then '/console/cases/' || ticket_record.case_id::text
    else '/console/tickets/' || ticket_record.id::text end;

  insert into public.user_notifications (user_id, kind, title, message, link, event_key)
  select target.user_id, lower(new.action), notification_title, notification_message, destination,
    'ticket-activity:' || new.id::text
  from (
    select ticket_record.created_by_user_id user_id
    union select ticket_record.responsible_manager_id
    union select assignment.user_id from public.crm_ticket_assignments assignment
      where assignment.ticket_id = new.ticket_id and assignment.removed_at is null
  ) target
  join public.profiles profile on profile.id = target.user_id and profile.status = 'active'
  where target.user_id is distinct from new.actor_user_id
  on conflict (user_id, event_key) do nothing;
  return new;
end;
$$;

drop trigger if exists crm_notify_permission_request_created on public.crm_ticket_permission_requests;
create trigger crm_notify_permission_request_created
after insert on public.crm_ticket_permission_requests
for each row execute function public.crm_notify_permission_request_created();

drop trigger if exists crm_notify_permission_request_reviewed on public.crm_ticket_permission_requests;
create trigger crm_notify_permission_request_reviewed
after update of status on public.crm_ticket_permission_requests
for each row execute function public.crm_notify_permission_request_reviewed();

drop trigger if exists crm_notify_ticket_activity on public.crm_ticket_activity;
create trigger crm_notify_ticket_activity
after insert on public.crm_ticket_activity
for each row execute function public.crm_notify_ticket_activity();

create or replace function public.get_user_notifications(p_limit integer default 40)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare actor uuid := (select auth.uid());
begin
  if actor is null then raise exception 'Authentication required'; end if;
  return jsonb_build_object(
    'unreadCount', (select count(*) from public.user_notifications where user_id = actor and read_at is null),
    'items', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', notification.id,
        'kind', notification.kind,
        'title', notification.title,
        'message', notification.message,
        'link', notification.link,
        'readAt', notification.read_at,
        'createdAt', notification.created_at
      ) order by notification.created_at desc), '[]'::jsonb)
      from (
        select * from public.user_notifications
        where user_id = actor order by created_at desc limit least(greatest(p_limit, 1), 100)
      ) notification
    )
  );
end;
$$;

create or replace function public.mark_user_notifications_read(p_notification_id uuid default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := (select auth.uid()); affected integer;
begin
  if actor is null then raise exception 'Authentication required'; end if;
  update public.user_notifications set read_at = coalesce(read_at, now())
  where user_id = actor and (p_notification_id is null or id = p_notification_id);
  get diagnostics affected = row_count;
  return jsonb_build_object('updated', affected);
end;
$$;

revoke all on table public.user_notifications from public, anon, authenticated;
revoke all on function public.crm_notification_request_label(text) from public, anon, authenticated;
revoke all on function public.crm_notify_permission_request_created() from public, anon, authenticated;
revoke all on function public.crm_notify_permission_request_reviewed() from public, anon, authenticated;
revoke all on function public.crm_notify_ticket_activity() from public, anon, authenticated;
revoke all on function public.get_user_notifications(integer) from public, anon;
revoke all on function public.mark_user_notifications_read(uuid) from public, anon;
grant execute on function public.get_user_notifications(integer) to authenticated;
grant execute on function public.mark_user_notifications_read(uuid) to authenticated;
